### ISSUE TITLE
数据插入异常

### ISSUE THREAD

**Issue by B0y1n4o4** [jasonsheh/SiteScan#3]
在对网站标题扫描完，需要插入到数据库时, 由于标题带有`'`, 例如 `admin's blog` 插入数据的语句是
```
sql = "insert into subdomain (url, ip, title, appname, taskid) " \
                  "values ('%s', '%s', '%s', '%s', '%s')"\
                  % (url, ips, title[url], appname[url], taskid)
```

即可触发异常
```
Traceback (most recent call last):
  File "SiteScan.py", line 37, in <module>
    main()
  File "SiteScan.py", line 29, in main
    site_scan(args.domain)
  File "/home/xxxx/PycharmProjects/SiteScan/lib/factory.py", line 32, in site_scan
    domains, ips = Domain(domain, id).run()
  File "/home/xxxx/PycharmProjects/SiteScan/lib/subdomain.py", line 57, in run
    Database().insert_subdomain(self.domains, self.title, self.appname, self.id)
  File "/home/xxxx/PycharmProjects/SiteScan/database/database.py", line 166, in insert_subdomain
    self.cursor.execute(sql)
sqlite3.OperationalError: near "Blog": syntax error
```
成**SQL注入**了。。。

**Comment by jasonsheh** [comment]
感谢！

已经把所有的数据库操作全部改为参数化语句了，应该不存在注入的问题，含有特殊符号的内容应该也可以存储了
